#!/usr/bin/env bash

walldir="$HOME/MEGA/WallHaven"
cachedir="$HOME/.cache/wallhaven"

categories="${2:-010}"
purity="${1:-100}"
sorting="random"
atleast="1920x1080"
ratios="16x9"
seed="[a-zA-Z0-9]{6}"

max_pages=${3:-3}
apikey="xkTtX4xkWoXATYW1v1GF4fQfy3FWhnoR"
quality="large"

sh_menu () {
	: | dmenu -p "search wallhaven:" -h 24 -c
}

declare -a args=$*
[ -n "$4" ] && query=${args:10} || query=$( sh_menu )
[ -z "$query" ] && exit 1
query=$(printf '%s' "$query" | tr ' ' '+' )

rm -rf "$cachedir"
mkdir -p "$walldir" "$cachedir"

sh_info () {
	printf "%s\n" "$1" >&2
	[ -n "$2" ] && exit "$2"
}

dep_ck () {
	for dep; do
		command -v "$dep" >/dev/null 2>&1 || sh_info "command $dep not found, install: $dep" 1
	done
}
dep_ck "sxiv" "curl" "jq"

clean_up () {
	printf "%s\n" "cleaning up..." >&2
	rm -rf "$datafile" "$cachedir"
}

datafile="/tmp/wald.$$"

trap "exit" INT TERM
trap "clean_up" EXIT

get_results () {
	for page_no in $(seq "$max_pages")
	do
		{
			json=$(curl -s -G "https://wallhaven.cc/api/v1/search?apikey=$apikey" \
				       -d "q=$1" \
				       -d "categories=$categories" \
				       -d "purity=$purity" \
				       -d "sorting=$sorting" \
				       -d "atleast=$atleast" \
				       -d "ratios=$ratios" \
				       -d "page=$page_no" \
				       -d "seed=$seed"
				)
			printf "%s\n" "$json" >> "$datafile"
		} &
		sleep 0.001
	done
	wait
}

sh_info "getting data..."
get_results "$query"

[ -s "$datafile" ] || sh_info "no images found" 1 

thumbnails=$( jq -r '.data[]?|.thumbs.'"$quality" < "$datafile")

[ -z "$thumbnails" ] && sh_info "no-results found" 1

sh_info "caching thumbnails..."
for url in $thumbnails
do
		printf "url = %s\n" "$url"
		printf "output = %s\n" "$cachedir/${url##*/}"
done | curl -Z -K -

image_ids="$(sxiv -tfpo -z 400 "$cachedir")"
[ -z "$image_ids" ] && exit

cd "$walldir" || exit
sh_info "downloading wallpapers..."
for ids in $image_ids
do
	ids="${ids##*/}"
	ids="${ids%.*}"
	# shellcheck disable=SC2086
	url=$( jq -r '.data[]?|select( .id == "'$ids'" )|.path' < "$datafile" )
	printf "url = %s\n" "$url"
	printf -- "-O\n"
done | curl -K -

sh_info "wallpapers downloaded in:- '$walldir'"
# shellcheck disable=SC2046
sxiv $(ls -c)
